BITMAP_BOUNDING_RECT_BASE_X_DEFAULT = -10.0
BITMAP_BOUNDING_RECT_BASE_Y_DEFAULT = -10.0

BITMAP_BOUNDING_RECT_EXTENT_X_DEFAULT = 20.0
BITMAP_BOUNDING_RECT_EXTENT_Y_DEFAULT = 20.0

BITMAP_BOUNDING_RECT_BASE_X_MIN = - 1000.0
BITMAP_BOUNDING_RECT_BASE_X_MAX = 1000.0

BITMAP_BOUNDING_RECT_BASE_Y_MIN = -1000.0
BITMAP_BOUNDING_RECT_BASE_Y_MAX = 1000.0

BITMAP_BOUNDING_RECT_EXTENT_X_MIN = -2000.0
BITMAP_BOUNDING_RECT_EXTENT_X_MAX = 2000.0

BITMAP_BOUNDING_RECT_EXTENT_Y_MIN = -2000.0
BITMAP_BOUNDING_RECT_EXTENT_Y_MAX = 2000.0

